### ISSUE TITLE
New Discoveries and the user profile

### ISSUE THREAD

**Issue by djehmli** [jaszhix/NoMansConnect#78]
Trying to test this portion of the new Readme:

**Added user profiles. Accessible by clicking a user's badge.**

    All discoveries are now uploaded to the server - this includes flora, fauna, planets, and systems. These are then associated with registered locations. The only way to uniquely identify a discovery in the save file this way is by manually naming it in-game

I have uploaded a handful of locations after using the X renaming in game for the system.  Example would be DJS00001, DJP00001, DJP00002, DJM00003 etc.  (and I was luckily online from a discovery aspect in NMS as well)

But I do not see anything added to the regular 'system' card.  Also does the requirement for 'naming' also mean at the flora and fauna level?  For example I used the x to rename the planet, do I also have to have a manual name for all the flora and fauna or do they piggy back the system/planets?

**NOTES:**
Windows 10
C:\Users\\djehm\AppData\Roaming\HelloGames\NMS\st_76561198052970098
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky

**NMC Log**
_Sun Jul 29 2018 18:59:31 GMT-0400 (Eastern Daylight Time):    "getLastSave -> next -> Error: Request failed with status code 500,Request failed with status code 500,Error: Request failed with status code 500\n    at module.exports (file:///C:/Users/djehm/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2070121)\n    at module.exports (file:///C:/Users/djehm/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2072459)\n    at XMLHttpRequest.request.(anonymous function) (file:///C:/Users/djehm/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2063943)\n    at XMLHttpRequest.wrapped (file:///C:/Users/djehm/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:3716682)"
Sun Jul 29 2018 18:59:44 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:10:21 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:10:35 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:28:58 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:29:12 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:29:52 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:30:07 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:37:03 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:37:18 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:38:18 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:38:33 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:45:19 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Sun Jul 29 2018 19:45:34 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Mon Jul 30 2018 11:53:42 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 1.2.0"
Mon Jul 30 2018 11:53:50 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Mon Jul 30 2018 11:53:50 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\save.hg"
Mon Jul 30 2018 11:53:50 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Mon Jul 30 2018 11:53:50 GMT-0400 (Eastern Daylight Time):    "Current location: -1722:-9:-41:183:320:1"
Mon Jul 30 2018 14:01:16 GMT-0400 (Eastern Daylight Time):    null
Mon Jul 30 2018 14:01:17 GMT-0400 (Eastern Daylight Time):    null
Mon Jul 30 2018 14:01:17 GMT-0400 (Eastern Daylight Time):    null
Mon Jul 30 2018 14:15:35 GMT-0400 (Eastern Daylight Time):    "Initializing No Man's Connect 1.2.0"
Mon Jul 30 2018 14:15:36 GMT-0400 (Eastern Daylight Time):    "Finished reading No Man's Sky v4626 save file."
Mon Jul 30 2018 14:15:36 GMT-0400 (Eastern Daylight Time):    "Active save file: C:\\Users\\djehm\\AppData\\Roaming\\HelloGames\\NMS\\st_76561198052970098\\save.hg"
Mon Jul 30 2018 14:15:36 GMT-0400 (Eastern Daylight Time):    "Username: djehmli"
Mon Jul 30 2018 14:15:36 GMT-0400 (Eastern Daylight Time):    "Current location: -1722:-9:-41:183:320:1"_

**Comment by jaszhix** [comment]
This happens when the remote locations list gets out of sync - there's a nasty bug causing the JSON file to get corrupted that I just fixed. I reproduced your issue earlier today and I would be curious if it occurs on the version I'm about to upload. I haven't seen this affect server data though, usually a full deletion of AppData/Roaming/NoMansConnect resolves it temporarily. 

There's also errors I have been seeing related to discoveries, some people have emailed me saying their discoveries are not uploading - I applied a fix on the server for that, and have another server patch I'm going to deploy soon. 

To clear up the issue with "locations" vs discoveries - the two data models are associated but its not really being used for anything useful yet, except for being able to put a picture to an arbitrary flower/animal you discovered somewhere. The discoveries should not be mutating the location data in anyway. The NMC name/description is not shown on the profile with the discoveries they're connected to yet, but the data is there, its just a process of reconciling old and new code.

**Comment by djehmli** [comment]
thank you so much.  I, as always, appreciate your time and effort.  I am extremely happy you were able to duplicate the issue.  Now if only the same were true for my real life job :)

**Comment by jaszhix** [comment]
No problem! By the way, I sort of skipped your comment about the bot profile. Its not me, and if it is indeed a bot I would ban it since that takes some of the fun/legitimacy from the data, but not sure, it could just be a [CLAN] name.

**Comment by djehmli** [comment]
Just an update, downloaded the latest, flushed appdata and so far so good.  Going to try to 're discover' the two planets which I still show discovered in game, but you don't have.  The Bot aspect was wiered, as they just popped in and out from 0 to 43 discoveries, I followed their trail and it looked like they were just porting from one location to another.  Since I hop galaxies using a hyperdrive mod (usually have patience for 13 or fourteen systems before I get bored and want to see the next center) it appeared the bot ported to me, then ported to the next galaxy and so on.  Why I thought it may be you using a tester was the way their data just disappeared shortly there after.  No longer on the Recent discovery and no longer on the maps as a hover.

Regardless, all is well that seems to have ended well.
